name: ui-test-action
run-name: Check test
on: [push]

jobs:
  setup-flutter:
    name: Setup Flutter sdk and environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.0.2

  flutte-test:
    name: Run Flutter test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run test
        run: flutter test
