name: ui-test-action
run-name: Pre checks
on: [push]

jobs:
  analyze-and-test:
    name: Checks flutter analyze and unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.22.0
          cache: true # Enable caching for pub dependencies

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit test
        run: flutter test
