name: ui-test-action
run-name: running UI unit testing
on: [push]
jobs:
  run-analyze:
    name: Run Flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run Public flutter analyze
        uses: NIOMIND-srl-sb/flutter-analyze-action@v1.0.20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
