name: ui-test-action
run-name: Check test
on: [push]

jobs:
  setup-flutter:
    name: Setup Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0

  flutte-test:
    name: Run Flutter test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run test
        run: flutter test
