name: ui-test-action
run-name: Check test
on: [push]

jobs:
  setup-flutter:
    name: Setup Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v3.6
        with:
          channel: "stable"
          version: "2.19.0"

  flutte-test:
    name: Run Flutter test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run test
        run: flutter test
