name: ui-test-action
run-name: Pre checks
on: [push, pull_request]

jobs:
  analyze-and-test:
    name: Checks flutter analyze and unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.22.0
          cache: true # Enable caching for pub dependencies
          cache-sdk: true # Enable caching for Flutter SDK

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit test
        run: flutter test

  notify-in-slack:
    name: Notifies reviewer in slack
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Extract PR information
        run: |
          echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event}}" >> $GITHUB_ENV
